import {exportContacts,prepareContactImport} from './contacts.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const $=id=>document.getElementById(id);
const download=(name,data,type)=>{const url=URL.createObjectURL(new Blob([data],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
export function contactToolbar({key,records,state,editionId='',dialog,commit,status}){
 const bar=document.createElement('div');bar.className='contact-tools';bar.innerHTML='<span>Transférer cet annuaire</span><button data-export="csv">Exporter CSV</button><button data-export="json">Exporter JSON</button><label class="file-button">Importer CSV / JSON<input type="file" accept=".csv,.json" aria-label="Importer cet annuaire"></label>';
 bar.onclick=e=>{const format=e.target.dataset.export;if(format)download(`${key}.${format}`,exportContacts(records,key,format),format==='csv'?'text/csv;charset=utf-8':'application/json');};
 bar.querySelector('input').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>10*1024*1024)throw Error('Fichier trop volumineux (10 Mo maximum).');const preview=prepareContactImport(await file.text(),file.name,key,state,editionId),plan=preview.planStats?`<strong>${preview.planStats.postsAdded} nouveaux postes</strong><strong>${preview.planStats.postsUpdated||0} postes mis à jour</strong><strong>${preview.planStats.assignmentsAdded} nouvelles affectations</strong><strong>${preview.planStats.assignmentsUpdated} affectations mises à jour</strong>${preview.planStats.aidStationsAdded!==undefined?`<strong>${preview.planStats.aidStationsAdded} nouveaux ravitaillements</strong><strong>${preview.planStats.aidStationsUpdated} ravitaillements mis à jour</strong>`:''}`:'';dialog.innerHTML=`<h2>Vérifier l’import</h2><p>${esc(file.name)}</p><div class="import-totals"><strong>${preview.added} nouvelles fiches</strong><strong>${preview.updated} mises à jour</strong>${plan}</div><p>Les fiches existantes sont mises à jour uniquement si leur identifiant correspond. Aucune fiche n’est supprimée.</p>${preview.warnings.length?`<div class="org-notice">${preview.warnings.slice(0,30).map(esc).join('<br>')}</div>`:''}<p>Colonnes CSV : Identifiant, Prénom, Nom, Éditions, Téléphone, Email, Notes${key==='volunteers'?', Actif, Visible publiquement, Historique':''}. Vous pouvez utiliser un export comme modèle.</p><p id="importError" role="alert"></p><div class="org-form-actions"><button id="cancelContactImport">Annuler</button><button id="confirmContactImport">Valider l’import</button></div>`;dialog.showModal();$('cancelContactImport').onclick=()=>dialog.close();$('confirmContactImport').onclick=async()=>{try{$('confirmContactImport').disabled=true;await commit(preview.next);dialog.close();status('Import terminé.');}catch(e){$('importError').textContent=e.message;$('confirmContactImport').disabled=false;}};}catch(e){status(e.message,true);}finally{e.target.value='';}};return bar;
}
export async function renderAccounts({repo,container,dialog,status,isCurrent=()=>true}){
 if(!repo.remote){container.innerHTML='<p>La gestion des comptes nécessite le serveur partagé.</p>';return;}
 const {users}=await repo.request('users');if(!isCurrent())return;container.innerHTML=`<p>Les administrateurs gèrent les comptes. Les organisateurs gèrent l’événement.</p><button id="addUser" class="primary-button">+ Nouvel utilisateur</button><div class="org-table-wrap"><table><thead><tr><th>Utilisateur</th><th>Identifiant</th><th>Rôle</th><th>État</th><th></th></tr></thead><tbody>${users.map(u=>`<tr><td>${esc(u.name)}</td><td>${esc(u.username)}</td><td>${u.role==='admin'?'Administrateur':'Organisateur'}</td><td>${u.active?'Actif':'Désactivé'}</td><td><button data-user="${esc(u.id)}">Modifier</button></td></tr>`).join('')}</tbody></table></div>`;
 function edit(u={role:'organizer',active:true}){dialog.innerHTML=`<form id="userForm" class="org-form"><h2>${u.id?'Modifier le compte':'Nouvel utilisateur'}</h2><label>Nom<input name="name" required value="${esc(u.name)}" maxlength="120"></label><label>Identifiant ou email<input name="username" required minlength="3" value="${esc(u.username)}" autocomplete="off"></label><label>Rôle<select name="role"><option value="organizer">Organisateur</option><option value="admin" ${u.role==='admin'?'selected':''}>Administrateur</option></select></label><label class="org-check"><input name="active" type="checkbox" ${u.active?'checked':''}>Compte actif</label><label>${u.id?'Nouveau mot de passe (laisser vide pour le conserver)':'Mot de passe'}<input name="password" type="password" minlength="12" maxlength="256" ${u.id?'':'required'} autocomplete="new-password"></label><p>12 caractères minimum. Une modification du compte ferme ses sessions en cours.</p><p id="userError" role="alert"></p><div class="org-form-actions"><button type="button" id="cancelUser">Annuler</button><button>Enregistrer</button></div></form>`;dialog.showModal();$('cancelUser').onclick=()=>dialog.close();$('userForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);try{await repo.request('users',u.id?'PUT':'POST',{id:u.id,name:f.get('name'),username:f.get('username'),role:f.get('role'),active:f.has('active'),password:f.get('password')});if(u.id===repo.user?.id){location.reload();return;}dialog.close();await renderAccounts({repo,container,dialog,status,isCurrent});status('Compte enregistré.');}catch(e){$('userError').textContent=e.message;}};}
 $('addUser').onclick=()=>edit();container.onclick=e=>{const b=e.target.closest('[data-user]');if(b)edit(users.find(u=>u.id===b.dataset.user));};
}
export async function renderApplications({repo,container,editionId,state,reload,status,isCurrent=()=>true}){
 if(!repo.remote){container.innerHTML='<p>Les candidatures sont disponibles avec le serveur partagé.</p>';return;}
 const {applications}=await repo.request(`applications?editionId=${encodeURIComponent(editionId)}`);if(!isCurrent())return;container.innerHTML=`<div class="org-toolbar"><p>${applications.filter(a=>a.status==='nouveau').length} candidature(s) à traiter</p><button id="reloadApplications">Actualiser</button></div>${applications.map(a=>`<article class="application-card"><header><div><h3>${esc(a.firstName)} ${esc(a.lastName)}</h3><span>${esc(a.status)} · ${esc(new Date(a.createdAt).toLocaleDateString('fr-FR'))}</span></div></header><p>${esc(a.email)} · ${esc(a.phone)}</p><dl><dt>Disponibilités</dt><dd>${esc(a.availability||'Non précisées')}</dd><dt>Souhaits de mission</dt><dd>${esc(a.preference||'Aucun souhait particulier')}</dd><dt>Message</dt><dd>${esc(a.notes||'—')}</dd></dl>${a.status==='nouveau'?`<label>Fiche bénévole<select data-link="${esc(a.id)}"><option value="">Créer une nouvelle fiche</option>${state.volunteers.map(v=>`<option value="${esc(v.id)}">${esc(v.firstName)} ${esc(v.lastName)} · ${esc(v.email)}</option>`).join('')}</select></label><div class="org-form-actions"><button data-review="${esc(a.id)}" data-action="rejected">Ne pas retenir</button><button data-review="${esc(a.id)}" data-action="accepted">Accepter la candidature</button></div>`:''}</article>`).join('')||'<div class="dashboard-empty">Aucune candidature pour cette édition. Le formulaire « Devenir bénévole » est accessible dans l’espace public.</div>'}`;
 const refresh=()=>renderApplications({repo,container,editionId,state,reload,status,isCurrent});$('reloadApplications').onclick=()=>refresh().catch(e=>status(e.message,true));container.onclick=async e=>{const b=e.target.closest('[data-review]');if(!b)return;try{b.disabled=true;const select=[...container.querySelectorAll('[data-link]')].find(s=>s.dataset.link===b.dataset.review);await repo.request('applications/review','POST',{id:b.dataset.review,action:b.dataset.action,volunteerId:select?.value||undefined});await reload();}catch(e){b.disabled=false;status(e.message,true);}};
}
export function renderAccount({repo,container}){container.innerHTML=`<form id="passwordForm" class="org-form narrow-form"><h3>Changer mon mot de passe</h3><label>Mot de passe actuel<input type="password" name="currentPassword" autocomplete="current-password" required></label><label>Nouveau mot de passe<input type="password" name="password" minlength="12" maxlength="256" autocomplete="new-password" required></label><label>Confirmer le nouveau mot de passe<input type="password" name="confirmation" minlength="12" autocomplete="new-password" required></label><p id="passwordError" role="alert"></p><button>Enregistrer et me reconnecter</button></form>`;$('passwordForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);if(f.get('password')!==f.get('confirmation')){$('passwordError').textContent='Les deux mots de passe doivent être identiques.';return;}try{await repo.request('account','PUT',{currentPassword:f.get('currentPassword'),password:f.get('password')});location.reload();}catch(e){$('passwordError').textContent=e.message;}};}
