import {uid,validate,normalize} from './domain.js';
export const contactFields={volunteers:['id','firstName','lastName','editionIds','phone','email','notes','active','organizationMember','publicVisible','history'],owners:['id','firstName','lastName','phone','email','landRole','referentId','agreementStatus','thankedStatus','notes']};
export const headings={id:'Identifiant',firstName:'Prénom',lastName:'Nom',editionIds:'Éditions',phone:'Téléphone',email:'Email',notes:'Notes',active:'Actif',organizationMember:'Membre organisation',publicVisible:'Visible publiquement',history:'Historique',landRole:'Statut',referentId:'Référent',agreementStatus:'Accord',thankedStatus:'Remercié'};
export function exportContacts(records,key,format){if(format==='json')return JSON.stringify({type:key,version:1,records},null,2);const cell=value=>'"'+String(value??'').replace(/^[=+@\-\t\r]/,"'$&").replaceAll('"','""')+'"';return '\ufeff'+[contactFields[key].map(f=>headings[f]),...records.map(r=>contactFields[key].map(f=>typeof r[f]==='object'?JSON.stringify(r[f]):typeof r[f]==='boolean'?r[f]?'oui':'non':r[f]??''))].map(r=>r.map(cell).join(';')).join('\r\n');}
export function parseCSV(text){text=text.replace(/^\uFEFF/,'');const first=text.split(/\r?\n/,1)[0],delimiter=(first.match(/;/g)||[]).length>=(first.match(/,/g)||[]).length?';':',';let rows=[],row=[],cell='',quoted=false;
 for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++;}else quoted=!quoted;}else if(!quoted&&c===delimiter){row.push(cell);cell='';}else if(!quoted&&(c==='\n'||c==='\r')){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(c=>c!==''))rows.push(row);row=[];cell='';}else cell+=c;}if(quoted)throw Error('CSV invalide : guillemets non fermés.');row.push(cell);if(row.some(c=>c!==''))rows.push(row);return rows;
}
export function prepareContactImport(text,fileName,key,state,editionId=''){if(!contactFields[key])throw Error('Import non autorisé.');text=text.replace(/^\uFEFF/,'');let incoming,bundle;
 if(/\.json$/i.test(fileName)){const data=JSON.parse(text);bundle=key==='volunteers'&&data.type==='volunteer-plan'?data:null;if(data.type&&data.type!==key&&!bundle)throw Error('Ce fichier concerne un autre annuaire.');incoming=bundle?data.volunteers:Array.isArray(data)?data:data.records||data[key];}
 else {const matrix=parseCSV(text);if(matrix.length<2)throw Error('Le fichier ne contient aucune fiche.');const aliases=Object.fromEntries(Object.entries(headings).flatMap(([k,v])=>[[normalize(k),k],[normalize(v),k]]));Object.assign(aliases,{prenom:'firstName',nom:'lastName',telephone:'phone',commentaire:'notes','e-mail':'email'});const fields=matrix[0].map(h=>aliases[normalize(h.trim())]);if(!fields.includes('lastName'))throw Error('Colonne « Nom » manquante.');if(fields.filter(Boolean).length!==new Set(fields.filter(Boolean)).size)throw Error('Colonnes en double.');incoming=matrix.slice(1).map((r,i)=>{if(r.length!==fields.length)throw Error(`Ligne ${i+2} : nombre de colonnes incorrect.`);return Object.fromEntries(fields.flatMap((f,n)=>f?[[f,r[n]]]:[]));});}
 if(!Array.isArray(incoming)||!incoming.length||incoming.length>10000)throw Error('Le fichier doit contenir de 1 à 10 000 fiches.');const next=structuredClone(state),seen=new Set();let added=0,updated=0,warnings=[];
 for(const [index,raw] of incoming.entries()){if(!raw||typeof raw!=='object')throw Error(`Fiche ${index+1} invalide.`);const row=Object.fromEntries(contactFields[key].filter(k=>raw[k]!==undefined).map(k=>[k,raw[k]]));const id=String(row.id||uid());if(seen.has(id))throw Error(`Identifiant répété à la fiche ${index+1}.`);seen.add(id);const existing=next[key].find(v=>v.id===id);for(const k of ['firstName','lastName','phone','email','notes'])if(row[k]!==undefined)row[k]=String(row[k]).trim();
  if(!/\.json$/i.test(fileName))for(const k of ['firstName','lastName','phone','email','notes'])if(typeof row[k]==='string')row[k]=row[k].replace(/^'(?=[=+@\-\t\r])/,'');
  if(key==='volunteers'){for(const k of ['active','organizationMember','publicVisible'])if(row[k]!==undefined){const v=normalize(row[k]);if(!['true','false','oui','non','1','0',''].includes(v))throw Error(`Fiche ${index+1} : valeur oui/non attendue.`);row[k]=['true','oui','1'].includes(v);}for(const k of ['editionIds','history'])if(typeof row[k]==='string')row[k]=row[k].trim()?JSON.parse(row[k]):[];if(row.editionIds&&!Array.isArray(row.editionIds)||row.history&&!Array.isArray(row.history))throw Error('Liste d’éditions ou historique invalide.');}
  if(row.email&&next[key].some(v=>v.id!==id&&normalize(v.email)===normalize(row.email)))warnings.push(`Fiche ${index+1} : email déjà présent ; vérifiez qu’il ne s’agit pas d’un doublon.`);
  const record={...(key==='volunteers'?{active:true,organizationMember:false,publicVisible:false,editionIds:editionId?[editionId]:state.editions.map(e=>e.id),history:[]}:{landRole:'owner',referentId:'',agreementStatus:'to_contact',thankedStatus:'todo'}),...existing,...row,id};if(existing){next[key][next[key].indexOf(existing)]=record;updated++;}else {next[key].push(record);added++;}
 }
 let planStats=null;if(bundle){if(!Array.isArray(bundle.posts)||!Array.isArray(bundle.assignments))throw Error('Plan bénévoles incomplet.');const postIds=new Map();let postsAdded=0,postsUpdated=0,assignmentsAdded=0,assignmentsUpdated=0,aidStationsAdded=0,aidStationsUpdated=0;
  for(const raw of bundle.posts){const post=structuredClone(raw),existing=next.posts.find(p=>p.id===post.id)||(post.editionId&&next.posts.find(p=>p.editionId===post.editionId&&String(p.number)===String(post.number)));if(existing){next.posts[next.posts.indexOf(existing)]={...existing,...post,id:existing.id};postIds.set(post.id,existing.id);postsUpdated++;}else{next.posts.push(post);postIds.set(post.id,post.id);postsAdded++;}}
  for(const raw of bundle.assignments){const assignment=structuredClone(raw);assignment.postId=postIds.get(assignment.postId)||assignment.postId;const existing=next.assignments.find(a=>a.id===assignment.id);if(existing){next.assignments[next.assignments.indexOf(existing)]={...existing,...assignment};assignmentsUpdated++;}else{next.assignments.push(assignment);assignmentsAdded++;}}
  for(const raw of bundle.aidStations||[]){const aid=structuredClone(raw);aid.postId=postIds.get(aid.postId)||aid.postId;const existing=next.aidStations.find(a=>a.id===aid.id)||(aid.editionId&&next.aidStations.find(a=>a.editionId===aid.editionId&&String(a.number)===String(aid.number)));if(existing){next.aidStations[next.aidStations.indexOf(existing)]={...existing,...aid,id:existing.id};aidStationsUpdated++;}else{next.aidStations.push(aid);aidStationsAdded++;}}
  planStats={postsAdded,postsUpdated,assignmentsAdded,assignmentsUpdated,aidStationsAdded,aidStationsUpdated};
 }
 validate(next);return {next,added,updated,warnings,planStats};
}
