param([string]$Workbook='',[string]$Output='imports/benevoles-hiver-2026.json')
$ErrorActionPreference='Stop';Add-Type -AssemblyName System.IO.Compression.FileSystem
if(!$Workbook){$Workbook=(Get-ChildItem -File -Filter '*hiver*.xlsx'|Select-Object -First 1 -ExpandProperty FullName)}
if(!$Workbook){throw 'Fichier Excel hiver introuvable.'}
function Read-Rows($path){$zip=[IO.Compression.ZipFile]::OpenRead((Resolve-Path -LiteralPath $path).Path);try{$shared=@();$e=$zip.Entries|Where-Object FullName -eq 'xl/sharedStrings.xml';if($e){$r=[IO.StreamReader]::new($e.Open());[xml]$x=$r.ReadToEnd();$r.Close();foreach($i in $x.sst.si){$shared+=[string]$i.InnerText}};$e=$zip.Entries|Where-Object FullName -eq 'xl/worksheets/sheet1.xml';$r=[IO.StreamReader]::new($e.Open());[xml]$sheet=$r.ReadToEnd();$r.Close();foreach($row in $sheet.worksheet.sheetData.row|Select-Object -Skip 1){$c=@{};foreach($cell in $row.c){$col=$cell.r-replace'\d','';$c[$col]=if($cell.t-eq's'){[string]$shared[[int]$cell.v]}elseif($cell.t-eq'inlineStr'){[string]$cell.is.InnerText}elseif($cell.v){[string]$cell.v}else{''}};[pscustomobject]$c}}finally{$zip.Dispose()}}
function Norm($v){((([string]$v).Normalize([Text.NormalizationForm]::FormD)-replace'\p{Mn}','').ToLowerInvariant()-replace'[^a-z0-9]+',' ').Trim()}
function Time($v){$m=[regex]::Match(([string]$v).Replace([char]0xA0,' '),'(?i)(\d{1,2})h(?:([0-5]\d))?\s*-\s*(\d{1,2})h(?:([0-5]\d))?');if(!$m.Success){return @{}};@{start=('{0:d2}:{1:d2}'-f[int]$m.Groups[1].Value,$(if($m.Groups[2].Value){[int]$m.Groups[2].Value}else{0}));end=('{0:d2}:{1:d2}'-f[int]$m.Groups[3].Value,$(if($m.Groups[4].Value){[int]$m.Groups[4].Value}else{0}))}}
$people=@{};$rows=@();foreach($line in Read-Rows $Workbook|Where-Object{$_.A-and$_.B}){$k=Norm($line.B+' '+$line.A);if(!$people.ContainsKey($k)){$email=if(([string]$line.C)-match'@'){([string]$line.C).Trim().ToLowerInvariant()}else{''};$notes=@($(if($line.E){'Souhait / remarque : '+$line.E}),$(if($line.C-and-not$email){'Information de contact : '+$line.C}))|Where-Object{$_};$people[$k]=[ordered]@{key=$k;firstName=(Get-Culture).TextInfo.ToTitleCase(([string]$line.B).Trim().ToLower());lastName=([string]$line.A).Trim().ToUpperInvariant();phone=([string]$line.D).Trim();email=$email;notes=$notes-join"`n"}};$t=Time $line.I;$mission=(([string]$line.G).Trim()-replace'(?i)\s+\d{1,2}h(?:[0-5]\d)?\s*-\s*\d{1,2}h(?:[0-5]\d)?\s*$','');if(!$mission){$mission='Mission à préciser'};$rows+=[ordered]@{key=$k;mission=$mission;location=([string]$line.H).Trim();start=$t.start;end=$t.end}}
$plan=[ordered]@{source='Copie de Bénévoles hiver 2026.xlsx';volunteers=@($people.Values);rows=$rows};$parent=Split-Path -Parent $Output;if($parent-and-not(Test-Path $parent)){New-Item -ItemType Directory -Path $parent|Out-Null};$plan|ConvertTo-Json -Depth 6|Set-Content -LiteralPath $Output -Encoding utf8;Write-Output("{0} bénévoles, {1} lignes de planning"-f$people.Count,$rows.Count)
